name: Build Nvidia Streamline SDK (Windows x64)

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - main # Or your primary development branch
  pull_request:
    branches:
      - main # Or your primary development branch

jobs:
  build-streamline-windows-x64:
    runs-on: windows-latest # Use the latest Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # [2, 4]
        with:
          submodules: 'recursive' # Streamline uses submodules, this is crucial

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2 # [1, 17]
        with:
          cmake-version: '3.25.x' # Streamline requires 3.17+, specify a recent version

      - name: Configure CMake
        shell: pwsh # Use PowerShell, default on Windows runners
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64
        # -S . specifies the source directory is the current directory.
        # -B build specifies the build directory.
        # -G "Visual Studio 17 2022" tells CMake to generate VS 2022 project files.
        # -A x64 specifies the x64 architecture.

      - name: Build Streamline
        shell: pwsh
        run: |
          cmake --build build --config Release --parallel
        # --config Release specifies a release build.
        # --parallel enables parallel compilation for faster builds.

      - name: Install Streamline (Prepare Artifacts)
        shell: pwsh
        run: |
          cmake --install build --prefix ./streamline_sdk_output --config Release
        # This command installs the built components (libraries, headers, etc.)
        # into the 'streamline_sdk_output' directory in the workspace. [7, 11]

      - name: Upload Streamline SDK Artifact
        uses: actions/upload-artifact@v4 # [3, 5, 15]
        with:
          name: streamline-sdk-windows-x64-release
          path: ./streamline_sdk_output # Path to the directory created by the install step
          if-no-files-found: error # Fail the workflow if no files were found to upload
