name: Build and Upload NVIDIA Streamline (Windows x64)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'
          msbuild-architecture: 'x64'

      - name: Check Visual Studio Installation
        run: |
          $ErrorActionPreference = "Stop"
          # Check if vswhere is available
          if (-not (Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe")) {
            Write-Error "vswhere.exe not found. Visual Studio might not be installed properly."
          } else {
            & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version "[16.0,)" -products * -requires Microsoft.VisualStudio.Component.CoreEditor -property installationPath
          }

      - name: Override vswhere.exe with System Version
        run: |
          # Ensure that we replace the problematic vswhere.exe in the repository with the working one from Visual Studio
          $SystemVsWhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
          $StreamlineVsWhere = "${{ github.workspace }}\tools\vswhere.exe"
          
          if (Test-Path $StreamlineVsWhere) {
            Write-Host "Replacing incompatible vswhere.exe with system version."
            Copy-Item -Path $SystemVsWhere -Destination $StreamlineVsWhere -Force
          } else {
            Write-Host "vswhere.exe not found in the Streamline tools folder."
          }

      - name: Set VS_PATH manually if needed
        run: |
          # Check if VS_PATH is set correctly, if not, manually set it.
          if (-not $env:VS_PATH) {
            Write-Host "Manually setting VS_PATH to installed Visual Studio path."
            set VS_PATH="C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          }
          Write-Host "VS_PATH is set to: $VS_PATH"

      - name: Build Streamline
        run: |
          .\build.bat
        working-directory: ${{ github.workspace }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamline-build
          path: |
            ${{ github.workspace }}/bin/x64/Release/*
            ${{ github.workspace }}/lib/x64/Release/*
            ${{ github.workspace }}/tools/*
          retention-days: 30
