name: Build and Upload NVIDIA Streamline (Windows x64)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'
          vs-installer: true

      - name: Build Streamline
        run: |
          .\build.bat
        working-directory: ${{ github.workspace }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamline-build
          path: |
            ${{ github.workspace }}/bin/x64/Release/*
            ${{ github.workspace }}/lib/x64/Release/*
            ${{ github.workspace }}/tools/*
          retention-days: 30
