name: Build and Upload NVIDIA Streamline (Windows x64)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Verify Visual Studio 2022 Installation
        run: |
          $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-Not (Test-Path $vswherePath)) {
            Write-Error "vswhere.exe not found. Visual Studio 2022 might not be installed."
            exit 1
          }
          $vsInstallPath = & $vswherePath -latest -version "[17.0,18.0)" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          Write-Output "VS_INSTALL_PATH=$vsInstallPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Build Streamline
        run: |
          # Invoke MSBuild directly with the Visual Studio path (avoiding 'call' command)
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets" /m /t:Build
        working-directory: ${{ github.workspace }}


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamline-build
          path: |
            ${{ github.workspace }}/bin/x64/Release/*
            ${{ github.workspace }}/lib/x64/Release/*
            ${{ github.workspace }}/tools/*
          retention-days: 30
