name: Build Nvidia Streamline for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    # Step 2: Set up Python (if required for dependencies)
    - name: Set up Python 3.x
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.x'

    # Step 3: Install Visual Studio Build Tools (No GPU dependencies)
    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--includeOptional --allWorkloads --add Microsoft.VisualStudio.Workload.NativeDesktop"

    # Step 4: Install CMake
    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    # Step 5: Configure build using CMake
    - name: Configure build using CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64

    # Step 6: Build with MSBuild
    - name: Build with MSBuild
      run: |
        msbuild streamline.sln /p:Configuration=Release /p:Platform=x64

    # Step 7: Upload build artifacts (Optional)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: streamline-build
        path: build/Release/
