name: Build and Upload NVIDIA Streamline (Windows x64)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'
          msbuild-architecture: 'x64'


      - name: Check Visual Studio Installation
        run: |
          $ErrorActionPreference = "Stop"
          # Check if vswhere is available and check if Visual Studio is installed
          if (-not (Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe")) {
            Write-Error "vswhere.exe not found. Visual Studio might not be installed properly."
          } else {
            & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version "[16.0,)" -products * -requires Microsoft.VisualStudio.Component.CoreEditor -property installationPath
          }

      - name: Set VS_PATH using System's vswhere.exe
        run: |
          # Using the system's vswhere.exe to set the correct VS_PATH
          $vswherePath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
          $VS_PATH = & $vswherePath -version "[16.0,)" -products * -requires Microsoft.VisualStudio.Workload.NativeDesktop -property installationPath
          if ($VS_PATH) {
            Write-Host "Visual Studio detected at: $VS_PATH"
            echo "VS_PATH=$VS_PATH" >> $GITHUB_ENV
          } else {
            Write-Error "Visual Studio not found!"
          }

      - name: Build Streamline
        run: |
          .\build.bat
        working-directory: ${{ github.workspace }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamline-build
          path: |
            ${{ github.workspace }}/bin/x64/Release/*
            ${{ github.workspace }}/lib/x64/Release/*
            ${{ github.workspace }}/tools/*
          retention-days: 30
